# Pre-task variables
galaxy_server_name: 'main_sanbi_galaxy1'
cephfs_mounts:
  - src: "/tools"
    dst: "/tools"
    id: "tools"
    key: "{{ lookup('hashi_vault', 'secret=secret/ansible/cephfs/tools:token') }}"
  - src: "/people"
    dst: "/usr/people"
    id: "people"
    key: "{{ lookup('hashi_vault', 'secret=secret/ansible/cephfs/people:token') }}"
  - src: "/projects/galaxy"
    dst: "/projects/galaxy"
    id: "projectsgalaxy"
    key: "{{ lookup('hashi_vault', 'secret=secret/ansible/cephfs/projectgalaxy:token') }}"
galaxy_server_dir: '/projects/galaxy/{{ galaxy_server_name }}'
galaxy_config_dir: "{{ galaxy_server_dir }}/config"
galaxy_user: galaxyuser
galaxy_group: galaxyuser
galaxy_config_style: yaml
galaxy_commit_id: 'release_19.01'
var_slurm_install_dir: "/tools/admin/slurm"
galaxy_config:
  uwsgi:
    socket: 127.0.0.1:4001
    buffer-size: 16384
    processes: 1
    threads: 4
    offload-threads: 2
    static-map:
      - /static/style={{ galaxy_server_dir }}/static/style/blue
      - /static={{ galaxy_server_dir }}/static
    master: true
    virtualenv: "{{ galaxy_venv_dir }}"
    pythonpath: "{{ galaxy_server_dir }}/lib"
galaxy_server_dir: '/projects/galaxy/{{ galaxy_server_name }}'
galaxy_config_dir: "{{ galaxy_server_dir }}/config"
galaxy_user: galaxyuser
galaxy_group: galaxyuser
galaxy_config_style: yaml
galaxy_commit_id: 'release_19.01'
var_slurm_install_dir: "/tools/admin/slurm"
galaxy_config:
  uwsgi:
    socket: 127.0.0.1:4001
    buffer-size: 16384
    processes: 1
    threads: 4
    offload-threads: 2
    static-map:
      - /static/style={{ galaxy_server_dir }}/static/style/blue
      - /static={{ galaxy_server_dir }}/static
    master: true
    virtualenv: "{{ galaxy_venv_dir }}"
    pythonpath: "{{ galaxy_server_dir }}/lib"
    module: 'galaxy.webapps.galaxy.buildapp:uwsgi_app()'
    thunder-lock: true
    die-on-term: true
    hook-master-start:
      - unix_signal:2 gracefully_kill_them_all
      - unix_signal:15 gracefully_kill_them_all
    py-call-osafterfork: true
    enable-threads: true
    mule:
      - lib/galaxy/main.py
      - lib/galaxy/main.py
    farm: 'job-handlers:1,2'
  galaxy:
    database_connection: "postgresql:///galaxyuser?host=/var/run/postgresql"
    admin_users: "eugene@sanbi.ac.za,pvh@sanbi.ac.za,thoba@sanbi.ac.za,zipho@sanbi.ac.za"
    nginx_x_accel_redirect_base: /_x_accel_redirect
    tool_sheds_config_file: "{{ galaxy_server_dir }}/config/tool_sheds_conf.xml"
    ftp_upload_dir: /tools/software/galaxy/upload_dirs/sanbi_galaxy1

postgresql_objects_users:
  - name: "{{ galaxy_user | default('galaxy') }}"
postgresql_objects_databases:
  - name: "{{ postgresql_objects_users[0]['name'] }}"
    owner: "{{ postgresql_objects_users[0]['name'] }}"
postgresql_version: 9.5
galaxy_use_singularity: true
singularity_command: "/tools/software/singularity-2.5.2/bin/singularity"
