# Pre-task variables
galaxy_server_dir: '/opt/galaxy/galaxy'
galaxy_config_dir: "{{ galaxy_server_dir }}/config"
galaxy_user: galaxy
galaxy_group: galaxy
galaxy_config_style: yaml
galaxy_commit_id: 'release_18.09'
galaxy_config:
  uwsgi:
    socket: 127.0.0.1:4001
    buffer-size: 16384
    processes: 1
    threads: 4
    offload-threads: 2
    static-map:
      - /static/style={{ galaxy_server_dir }}/static/style/blue
      - /static={{ galaxy_server_dir }}/static
    master: true
    virtualenv: "{{ galaxy_venv_dir }}"
    pythonpath: "{{ galaxy_server_dir }}/lib"
    module: 'galaxy.webapps.galaxy.buildapp:uwsgi_app()'
    thunder-lock: true
    die-on-term: true
    hook-master-start:
      - unix_signal:2 gracefully_kill_them_all
      - unix_signal:15 gracefully_kill_them_all
    py-call-osafterfork: true
    enable-threads: true
    mule: lib/galaxy/main.py
    mule: lib/galaxy/main.py
    farm: 'job-handlers:1,2'
  galaxy:
    database_connection: "postgresql:///galaxy?host=/var/run/postgresql"
    admin_users:

postgresql_objects_users:
  - name: "{{ galaxy_user | default('galaxy') }}"
postgresql_objects_databases:
  - name: "{{ postgresql_objects_users[0]['name'] }}"
    owner: "{{ postgresql_objects_users[0]['name'] }}"
postgresql_version: 9.5
