- name: Run JS generation scripts
  command: ./run.sh
  args:
    chdir: "{{ galaxy_server_dir }}"
  ignore_errors: yes
- name: Restart supervisord agent  
  supervisorctl:
    name: web
    state: restarted
