---
- name: Install Galaxy on Galaxy server
  hosts: galaxy
  tags: galaxy
  become: yes
  pre_tasks:
    - include_role:
        name: sanbi-ansible-role-common
    - include_role: # TODO: make this optional
        name: ansible-role-cephfs_client
      vars:
        cephfs_client_mapping: "{{ cephfs_mounts }}"
    - include_role:
        name: galaxy-bootstrap
  tasks:
    - name: Create PostgreSQL user and database
      include_role:
        name: natefoo.ansible-postgresql-objects
      vars:
        ansible_become: true
        ansible_become_user: postgres
    - name: Install Galaxy
      include_role:
        name: galaxyprojectdotorg.galaxy
      vars:
        ansible_become: true
        ansible_become_user: "{{ galaxy_user }}"
    - name: Ensure pyOpenSSL
      command: "python -m easy_install --upgrade pyOpenSSL"
    - name: Install supervisord
      include_role:
        name: galaxy-supervisord
    - name: Install nginx
      include_role:
        name: galaxy-nginx
    - name: Setup Slurm job submission for Galaxy
      include_role:
        name: galaxy-slurm-drmaa
  post_tasks:
    - name: force all notified handlers to run at this point, not waiting for normal sync points
      meta: flush_handlers
    - name: sleep for 300 seconds and continue with play
      wait_for: timeout=300
    - name: Generate JS
      include_role:
        name: galaxy-post
