---
- name: Install Galaxy on Galaxy server
  hosts: galaxy
  tags: galaxy
  become: yes
  pre_tasks:
    - include_role:
        name: galaxy-bootstrap
    - include_role:
        name: ansible-role-cephfs_client
      vars:
        cephfs_client_mapping:
          - {"src": "/projects/galaxy-dev", "dst": "/galaxy-dev", "id": "galaxy-dev", "key": ""}
          - {"src": "/projects/galaxy", "dst": "/galaxy", "id": "galaxy", "key": ""}
  tasks:
    - name: Create PostgreSQL user and database
      include_role:
        name: natefoo.ansible-postgresql-objects
      vars:
        ansible_become: true
        ansible_become_user: postgres
    - name: Install Galaxy
      include_role:
        name: galaxyprojectdotorg.galaxy
      vars:
        ansible_become: true
        ansible_become_user: "{{ galaxy_user }}"
    - name: Install supervisord
      include_role:
        name: galaxy-supervisord
    - name: Install nginx
      include_role:
        name: galaxy-nginx
  post_tasks:
    - name: force all notified handlers to run at this point, not waiting for normal sync points
      meta: flush_handlers
    - name: sleep for 300 seconds and continue with play
      wait_for: timeout=300
    - name: Generate JS
      include_role:
        name: galaxy-post
